import { defineCollection, z } from 'astro:content';

const incidents = defineCollection({
  type: 'content',
  glob: '**/*.{md,mdx}',
  schema: z.object({
    title: z.string(),
    date: z.date(),
    updated: z.date().optional(),
    summary: z.string().max(200),
    author: z.string().default('Dr. Anandkumar Prakasam'),
    tags: z.array(z.string()).default([]),
    status: z.enum(['draft', 'published']).default('draft'),
    featured: z.boolean().default(false),
    heroImage: z.string().optional(),
    ogImage: z.string().optional(),
    incidentDate: z.date(),
    systems: z.array(z.string()),
    domain: z.string(),
    severity: z.enum(['low', 'moderate', 'high', 'critical']),
    corroboration: z.string(),
    sources: z.array(z.object({
      label: z.string(),
      url: z.string(),
    })),
    timeline: z.array(z.object({
      date: z.date(),
      event: z.string(),
    })),
    rootCause: z.string(),
    contributoryFactors: z.array(z.string()),
    relatedPatterns: z.array(z.string()).default([]),
    relatedEssays: z.array(z.string()).default([]),
  }),
});

const essays = defineCollection({
  type: 'content',
  glob: '**/*.{md,mdx}',
  schema: z.object({
    title: z.string(),
    date: z.date(),
    updated: z.date().optional(),
    summary: z.string().max(200),
    author: z.string().default('Dr. Anandkumar Prakasam'),
    tags: z.array(z.string()).default([]),
    status: z.enum(['draft', 'published']).default('draft'),
    featured: z.boolean().default(false),
    heroImage: z.string().optional(),
    ogImage: z.string().optional(),
    category: z.enum(['essay', 'pattern']).default('essay'),
    series: z.enum([
      'human-in-control',
      'out-of-bounds',
      'accountable-autonomy',
      'six-dimensions',
      'the-burden',
    ]).optional(),
    seriesNo: z.number().optional(),
    readingTime: z.number().optional(),
    book: z.string().optional(),
    artifact: z.string().optional(),
    prev: z.string().optional(),
    next: z.string().optional(),
    linkedinUrl: z.string().optional(),
    mediumUrl: z.string().optional(),
    patentSensitive: z.boolean().default(false),
    patternId: z.string().optional(),
    signature: z.string().optional(),
    metric: z.string().optional(),
    relatedIncidents: z.array(z.string()).default([]),
  }),
});

const observations = defineCollection({
  type: 'content',
  glob: '**/*.{md,mdx}',
  schema: z.object({
    title: z.string(),
    date: z.date(),
    updated: z.date().optional(),
    summary: z.string().max(200),
    author: z.string().default('Dr. Anandkumar Prakasam'),
    tags: z.array(z.string()).default([]),
    status: z.enum(['draft', 'published']).default('draft'),
    featured: z.boolean().default(false),
    heroImage: z.string().optional(),
    ogImage: z.string().optional(),
    observationStatus: z.enum(['preliminary', 'ongoing', 'resolved']).default('preliminary'),
  }),
});

const artifacts = defineCollection({
  type: 'content',
  glob: '**/*.{md,mdx}',
  schema: z.object({
    title: z.string(),
    date: z.date(),
    updated: z.date().optional(),
    summary: z.string().max(200),
    author: z.string().default('Dr. Anandkumar Prakasam'),
    tags: z.array(z.string()).default([]),
    status: z.enum(['draft', 'published']).default('draft'),
    featured: z.boolean().default(false),
    heroImage: z.string().optional(),
    ogImage: z.string().optional(),
    artifactType: z.enum(['template', 'checklist', 'table', 'framework', 'worksheet', 'audit']),
    version: z.string(),
    relatedEssays: z.array(z.string()).default([]),
    relatedBook: z.string().optional(),
    inlinePreview: z.boolean().default(false),
    license: z.string().default('CC BY 4.0'),
    downloads: z.array(z.object({
      format: z.enum(['PDF', 'DOCX', 'XLSX', 'Markdown']),
      url: z.string(),
      sizeKB: z.number(),
    })),
  }),
});

const books = defineCollection({
  type: 'content',
  glob: '**/*.{md,mdx}',
  schema: z.object({
    title: z.string(),
    date: z.date(),
    updated: z.date().optional(),
    summary: z.string().max(200),
    author: z.string().default('Dr. Anandkumar Prakasam'),
    tags: z.array(z.string()).default([]),
    status: z.enum(['draft', 'published']).default('draft'),
    featured: z.boolean().default(false),
    heroImage: z.string().optional(),
    ogImage: z.string().optional(),
    cover: z.string(),
    series: z.string(),
    blurb: z.string(),
    toc: z.array(z.string()),
    pdfUrl: z.string(),
    pdfSizeMB: z.number(),
    amazonUrl: z.string(),
    isbn: z.string().optional(),
    pages: z.number().optional(),
  }),
});

export const collections = {
  incidents,
  essays,
  observations,
  artifacts,
  books,
};
